config/routes.rb
Rails.application.routes.draw do

  resources :useremails
  get 'static_pages/help'
  get 'static_pages/faq'
  root to: 'products#index'
  
  get '/about', to: 'about#index'
  
  resources :products, only: [:index, :show]
  resources :categories, only: [:show]

  resource :cart, only: [:show] do
    post   :add_item
    post   :remove_item
  end

  resources :orders, only: [:create, :show]

  namespace :admin do
    root to: 'dashboard#show'
    resources :products, except: [:edit, :update, :show]
    resources :categories, except: [:edit, :update, :show], skip: [:delete]
  end

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/signup', to: 'users#new'
  get '/register', to: 'users#new'
  post '/users', to: 'users#create'

end

app/models/useremail.rb
class Useremail < ApplicationRecord
end

app/controllers/useremails_controller.rb
class UseremailsController < ApplicationController
  before_action :set_useremail, only: %i[ show edit update destroy ]

  # GET /useremails or /useremails.json
  def index
    @useremails = Useremail.all
  end

  # GET /useremails/1 or /useremails/1.json
  def show
  end

  # GET /useremails/new
  def new
    @useremail = Useremail.new
  end

  # GET /useremails/1/edit
  def edit
  end

  # POST /useremails or /useremails.json
  def create
    @useremail = Useremail.new(useremail_params)

    respond_to do |format|
      if @useremail.save
        format.html { redirect_to useremail_url(@useremail), notice: "Useremail was successfully created." }
        format.json { render :show, status: :created, location: @useremail }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @useremail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /useremails/1 or /useremails/1.json
  def update
    respond_to do |format|
      if @useremail.update(useremail_params)
        format.html { redirect_to useremail_url(@useremail), notice: "Useremail was successfully updated." }
        format.json { render :show, status: :ok, location: @useremail }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @useremail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /useremails/1 or /useremails/1.json
  def destroy
    @useremail.destroy

    respond_to do |format|
      format.html { redirect_to useremails_url, notice: "Useremail was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_useremail
      @useremail = Useremail.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def useremail_params
      params.require(:useremail).permit(:first_name, :last_name, :email, :order_id)
    end
end

app/helpers/useremails_helper.rb
module UseremailsHelper
end

app/views/useremails/_form.html.erb
<%= form_with(model: useremail) do |form| %>
  <% if useremail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(useremail.errors.count, "error") %> prohibited this useremail from being saved:</h2>

      <ul>
        <% useremail.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :order_id %>
    <%= form.text_field :order_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/useremails/edit.html.erb
<h1>Editing Useremail</h1>

<%= render 'form', useremail: @useremail %>

<%= link_to 'Show', @useremail %> |
<%= link_to 'Back', useremails_path %>

app/views/useremails/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Useremails</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Order</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @useremails.each do |useremail| %>
      <tr>
        <td><%= useremail.first_name %></td>
        <td><%= useremail.last_name %></td>
        <td><%= useremail.email %></td>
        <td><%= useremail.order_id %></td>
        <td><%= link_to 'Show', useremail %></td>
        <td><%= link_to 'Edit', edit_useremail_path(useremail) %></td>
        <td><%= link_to 'Destroy', useremail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Useremail', new_useremail_path %>

app/views/useremails/new.html.erb
<h1>New Useremail</h1>

<%= render 'form', useremail: @useremail %>

<%= link_to 'Back', useremails_path %>

app/views/useremails/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @useremail.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @useremail.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @useremail.email %>
</p>

<p>
  <strong>Order:</strong>
  <%= @useremail.order_id %>
</p>

<%= link_to 'Edit', edit_useremail_path(@useremail) %> |
<%= link_to 'Back', useremails_path %>